# Generated by Django 4.0.3 on 2022-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Book_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Author_Name', models.CharField(max_length=100)),
                ('Publish_date', models.DateField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
